---
title: "RPractices"
author: "Titus"
date: "14/03/2021"
output: html_document
---

```{r}
dt1<-read.table(file.choose(),sep = ",",header = TRUE)
```

```{r}
dt1[1:4,]
```

```{r}
dt2<-read.table(file.choose(),sep = ",",header = F)
dt2[1:4,]
```

```{r}
dt3<-read.table(file.choose(),sep = "\t",header = F)
dt3
```

```{r}
dt4<-read.table(file.choose(),sep = ";",header = T)
dt4
```

```{r}
dt5<-read.csv(file.choose(),header = T)
dt5
```

```{r}
dt6<-read_excel(file.choose(),sheet = 1)
dt6
```

```{r}
dt7<-read_excel(file.choose(),sheet = 2)
dt7
```

```{r}
dt8<-read_sas(file.choose())
dt8[1:4,1:4]
```

```{r}
dta<-read_excel(file.choose(),skip = 1,
range = cell_cols(2:60))
dta[1:4,]
```

```{r}
dta_1<-dta %>% gather("2007-01":"2011-10",key = "year",value = "Passenger")
dta_1[1:100,]
```

```{r}
dta_2<-dta_1 %>% separate(year,into =c("year","month") )
dta_2[1:4,]
```

```{r}
dta_3<-dta_2 %>% spread(mode, Passenger)
dta_3[1:4,]
```

```{r}
dta_4<-dta_3 %>% .[,c(1:2,6:8)]
dta_4[1:4,]
```

```{r}
dta_5<-dta_4 %>% gather("Commuter Rail":"Light Rail",key ="Rail_Type",value = Passengers)
dta_5[1:100,]
```

```{r}
hflights[1:4,1:4]
```

```{r}
f1<-filter(hflights,Year==2011,Month==2)
f1[1:4,1:4]
```

```{r}
f2<-filter(hflights, Dest %in% c("BOS","LAS"))
f2[1:4,12:15]
```

```{r}
f3<-filter(hflights,between(Distance,224,944))
f3[1:6,13:16]
```

```{r}
clw<-filter(hflights,Year==2011,Month==4)
clw[1:4,1:4]
```

```{r}
clw2<-filter(hflights,UniqueCarrier %in% c("AA","WN"))
clw2[1:2,6:7]
```

```{r}
arr<-arrange(hflights,Year,Month)
arr[1:6,1:6]
```

```{r}
arr1<-arrange(hflights,desc(DepTime))
arr1[1:6,1:6]
```

```{r}
sel<-select(hflights,Year,Month,FlightNum,AirTime)
sel[1:4,]
```

```{r}
sel_2<-select(hflights,starts_with("Dep"),starts_with("Arr"))
sel_2[1:4,]
```

```{r}
m<-hflights%>%select(ends_with("Delay"),Distance,AirTime)%>%mutate(time_gain=ArrDelay-DepDelay,speed=Distance/AirTime * 60)
m[1:4,1:6]
```

```{r}
summarise(hflights,Delay=sum(DepDelay,na.rm = TRUE))
```

```{r}
hflights %>% group_by(UniqueCarrier) %>% summarise(delay =mean(DepDelay,na.rm=TRUE))
```

```{r}
hflights %>% group_by(UniqueCarrier) %>% summarise(DepDelay=n())
```

```{r}
gymdata<-read.csv(file.choose(),header = TRUE)
glimpse(gymdata)
```

```{r}
gymdata$Product<-as.factor(gymdata$Product)
gymdata$Gender<-as.factor(gymdata$Gender)
gymdata$MaritalStatus<-as.factor(gymdata$MaritalStatus)
```

```{r}
ggplot(gymdata,aes(x=Product,fill=Product))+geom_bar()+labs(x="Product",y="Frequency",title = "Distribution of Products")+geom_text(stat = "count",aes(label=..count..),vjust=0.3)
```

```{r}
p1<-ggplot(gymdata,aes(x=Income))+geom_histogram(color="black",fill="gray")+scale_x_continuous(labels = comma)+labs(title = "Histogram of Income",x="Income",y="Frequency")
p1
```

```{r}
p2<-ggplot(gymdata,aes(x=Income))+geom_boxplot(color="black",fill="grey")+scale_x_continuous(labels = comma)+labs(title= "Boxplot of Income",x="Income")
p2
```

```{r}
grid.arrange(p2, p1, heights = c(1, 1))
```

```{r}
p3<-ggplot(gymdata,aes(x=Product,fill=Gender))+geom_bar(position = "dodge")+labs(title = "Product Buyers By Gender",x="Products",y="Frequency")+geom_text(stat='count',aes(label=..count..)
,position=position_dodge(width=0.9),
vjust=-0.25)
p3
```

```{r}
p4<-ggplot(gymdata, aes(x=Product, y=Age, fill=Product)) +
geom_boxplot()+
labs(x= "Product", y= "Age",title="Product by Age")
p4
```

```{r}
data <- c(17,16, 20, 18, 16, 19, 22, 13 ,
15 ,17 ,21, 14, 18, 12)
result<-t.test(data, mu=20, alternative = "less")
result
```

```{r}
data2<-read.csv(file.choose(),header = T)


```

```{r}
result2<-t.test(data2$MorningClass,data2$EveningClass,alternative = "greater")
result2
```