---
title: "session1"
author: "Titus"
date: "12/03/2021"
output: html_document
---

```{r}
#Load Data
dt<-read.table("data_r\\who_1.csv",header = T,sep = ",")
head(dt)
```

```{r}
#Load Data
dt1<-read.table("data_r\\auto.txt",header = F,sep = ",")
head(dt1)
dt1[1:10,]
dt1[1:10,1:4]
names(dt1)<-c("cy1","Miles","Model","Fuel")
dt1[1:10,1:4]
```

```{r}
#Load Data
dt2<-read.table("data_r\\potatoes.txt",header = F,sep = "\t")
head(dt2)
dt2[1:10,]
dt2[1:10,1:4]
```

```{r}
#Load Data
dt3<-read.table("data_r\\who_2_semi.csv",header = T,sep = ";")
head(dt3)
dt3[1:10,]
dt3[1:10,1:4]
```

```{r}
#Load Data
dt4<-read.csv("data_r\\who_1.csv",header =T)
head(dt4)
dt4[1:10,]
dt4[1:10,1:4]
```

```{r}
#Load Data
dt5<-read.csv2("data_r\\who_2_semi.csv",header =T)
head(dt5)
dt5[1:10,]
dt5[1:10,1:4]
```

```{r}
#Load Data
dt6<-read.delim("data_r\\potatoes.txt",header =F)
head(dt6)
dt6[1:10,]
dt6[1:10,1:4]
```

```{r}
#Load Data
dt7<-readr::read_csv("data_r\\who_1.csv")
dt7[1:10,]
```

```{r}
#Load Data

dt8<-read_excel("data_r\\Employees.xlsx",sheet=1)
dt9<-read_excel("data_r\\Employees.xlsx",sheet=2)
dt8[1:4,1:4]
dt9[1:10,]
```

```{r}
host <- "courses.csrrinzqubik.us-east-1.rds.amazonaws.com"
connect <- dbConnect(RMySQL::MySQL(), dbname = "tweater",
host = host, port = 3306, user = "student", password =
"datacamp")
tables <- dbListTables(connect)
tables
users<-dbReadTable(connect,"users")
users
write.csv(users,"users.csv")
```

```{r}
house<-read.csv("https://factual.ng/course/house.csv",header = T)
house[1:4,1:4]

```

```{r}
birth <- read_sas("data_r\\birth1.sas7bdat")
birth[1:4,1:4]
```

```{r}
alcohol <- read_dta("data_r\\alcohol.dta")
alcohol[1:4,]

```

```{r}
pers <- read_sav("data_r\\librarapersonality.sav")
pers[1:4,]

```

```{r}
library(readxl)
library(tidyverse)
dtas<-read_excel("data_r\\mbta.xlsx",skip = 1,
range = cell_cols(2:60))
dtas[1:4,]
```

```{r}
dta_1 <- dtas %>% gather(`2007-01`:`2011-10`,
key = "year", value = "passengers")
dta_1[1:4,]
```

```{r}
dta_2<-dta_1 %>% separate(year,into = c("year","month"))
dta_2[1:4,]
```

```{r}
dta_3<- dta_1 %>% spread(mode,passengers)
dta_3[1:4,]
```

```{r}
dta_4 <- dta_3%>% .[,c(1:2,6:8)]
dta_4[1:4,]
```

#```{r}
#dta_5 <- dta_4 %>% gather("Heavy":"Light Rail",
#key="rail_type", value = passengers)
#dta_5[1:4,]
#```

```{r}
library(hflights)
data(hflights)
hflights[1:4,1:4]
```

```{r}
dta_5 <- dta_4 %>% gather("Heavy Rail":"Light Rail",
key="rail_type", value = passengers)
dta_5[1:4,]
```

```{r}
f1<-filter(hflights,Year==2011,Month==2)
f1[1:4,1:4]
```

```{r}
f1<-filter(hflights,Dest %in% c("BOS","LAS"))
f1[1:4,12:15]
```

```{r}
f1<-filter(hflights,between(Distance,224,944))
f1[1:6,13:16]
```

```{r}

f1<-filter(hflights,Year==2011,Month==4)
f1
```

```{r}
f2<-filter(hflights, UniqueCarrier %in% c("AA","WN"))
f2
```

```{r}
m<-hflights %>%
select(ends_with("Delay"), Distance, AirTime) %>%
mutate(time_gain = ArrDelay - DepDelay,
speed = Distance / AirTime * 60
)
m[1:4,1:6]
```

```{r}
summarise(hflights,Delay=sum(DepDelay,na.rm = TRUE))
```